openapi: 3.0.0
info:
    title: Online Education System APIs
    version: 1.0.0
    description: APIs for Online Education Systet

servers:
    - url: https://online-education-system-quch.onrender.com/api

paths:
    /auth/signup:
        post:
            summary: Register a new user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                    example: "Ali Ahmed"
                                email:
                                    type: string
                                    format: email
                                    example: "user@example.com"
                                password:
                                    type: string
                                    example: "P@ssw0rd123"
                                role:
                                    type: string
                                    enum: ["student", "teacher", "admin"]
                                    example: "student"
                                gender:
                                    type: string
                                    enum: ["male", "female"]
                                    example: "male"
                            required:
                                - name
                                - email
                                - password
                                - role
                                - gender
            responses:
                '201':
                    description: User created successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "User created successfully"
                '409':
                    description: Email already registered
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Email is already registered"
                '500':
                    description: Registration error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "An error occurred during registration"

    /auth/verify-email:
        post:
            summary: Verify user's email
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    format: email
                                    example: "user@example.com"
                                code:
                                    type: integer
                                    example: 12345
                            required:
                                - email
                                - code
            responses:
                '200':
                    description: Email verified successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Email verified successfully"
                                    token:
                                        type: string
                                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                '401':
                    description: Invalid verification code
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Invalid verification code"
                '404':
                    description: User not found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "User not found"
                '500':
                    description: Verification error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Verification process failed"

    /auth/login:
        post:
            summary: Authenticate user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    format: email
                                    example: "user@example.com"
                                password:
                                    type: string
                                    example: "P@ssw0rd123"
                            required:
                                - email
                                - password
            responses:
                '200':
                    description: Login successful
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Login successful"
                                    token:
                                        type: string
                                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                                    isBlocked:
                                        type: boolean
                                        example: false
                '401':
                    description: Invalid credentials
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Invalid password"
                '403':
                    description: Account not verified
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Account not verified"
                '404':
                    description: Email not registered
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Email not registered"
                '500':
                    description: Login error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Login process failed"

    /auth/send-code:
        post:
            summary: Send verification or reset code
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    format: email
                                    example: "user@example.com"
                                typeCode:
                                    type: string
                                    enum: ["verify", "reset"]
                                    example: "verify"
                            required:
                                - email
                                - typeCode
            responses:
                '201':
                    description: Code sent successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Code resent successfully"
                '404':
                    description: Email not registered
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Email not registered"
                '409':
                    description: Account not verified
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Email is not Verified"
                '500':
                    description: Error sending code
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "An error occurred during resend code"

    /auth/reset-password:
        post:
            summary: Reset user password
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    format: email
                                    example: "user@example.com"
                                code:
                                    type: integer
                                    example: 12345
                                newPassword:
                                    type: string
                                    example: "NewP@ssw0rd123"
                            required:
                                - email
                                - code
                                - newPassword
            responses:
                '200':
                    description: Password reset successful
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Password reset successfully"
                                    token:
                                        type: string
                                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                '401':
                    description: Invalid verification code
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Invalid verification code"
                '404':
                    description: User not found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "User not found"
                '409':
                    description: Account not verified
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Email is not Verified"
                '500':
                    description: Password reset error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Reset password process failed"